#define WLR_USE_UNSTABLE

#include "globals.hpp"
// version.hpp will be generated by meson
#include "customDecoration.hpp"
#include "customLayout.hpp"
#include "version.hpp"

#include <hyprland/src/Compositor.hpp>
#include <hyprland/src/Window.hpp>
#include <unistd.h>

// Do NOT change this function.
APICALL EXPORT std::string PLUGIN_API_VERSION() {
    return HYPRLAND_API_VERSION;
}

APICALL EXPORT PLUGIN_DESCRIPTION_INFO PLUGIN_INIT(HANDLE handle) {
    PHANDLE = handle;

    HyprlandAPI::reloadConfig();

    return {
        "hyprland-window-move",
        "Testing plugin adding xdg_top_level::move request handler",
        " horriblename",
        PLUGIN_VERSION
    };
}

APICALL EXPORT void PLUGIN_EXIT() {}
